name: KOMA
favicon: null
layout_spectrum: 0.1492893723770976
typography_spectrum: 0.9183208474423736
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.49753243778832257
  lightness: 0.5865839896723628
  saturation: 0.6852659254800528
  rhythmicContrast: 0.8639465784654021
purpose: []
